### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by hnguyen94** [justmoon/relative-numbers#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [relative-numbers](https://github.com/justmoon/relative-numbers) package, v0.5.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1460:35)
    at LineNumberView.module.exports.LineNumberView._updateSync (/Users/hoang-duc.nguyen/.atom/packages/relative-numbers/lib/line-number-view.coffee:89:33)
    at LineNumberView._updateSync (/Users/hoang-duc.nguyen/.atom/packages/relative-numbers/lib/line-number-view.coffee:1:1)
    at /Users/hoang-duc.nguyen/.atom/packages/relative-numbers/lib/line-number-view.coffee:85:40
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:215:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
  2x -0:10.9.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  8x -0:10.8.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:10.7.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  7x -0:10.6.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:10.6.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  7x -0:10.5.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:10.4.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  7x -0:10.3.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:10.3.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  7x -0:10.2.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  2x -0:10.1.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  2x -0:10.1.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:10 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode)
  6x -0:09.9.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:09.8.0 project-find-navigation:select-prev-and-confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
 10x -0:09.8.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "metrics",
      "jquery-snippets",
      "linter-eslint",
      "html2haml",
      "jshint",
      "autocomplete",
      "react",
      "background-tips",
      "welcome",
      "color-picker",
      "tree-view-git-status",
      "execute-as-ruby",
      "atom-fuzzy-grep"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify",
      "atom-terminal",
      "easy-motion-redux",
      "emmet",
      "git-projects",
      "preview-plus",
      "atom-material-ui",
      "ruby-block",
      "terminal-status",
      "recent-files-fuzzy-finder",
      "auto-indent",
      "split-diff",
      "rails-latest-migration",
      "valign",
      "execute-as-ruby",
      "color-picker",
      "tree-view-filter",
      "keybinding-cheatsheet",
      "terminal-plus",
      "git-blame",
      "rspec-tree-runner",
      "rspec",
      "rails-partials",
      "regex-railroad-diagram"
    ],
    "projectHome": "/Users/hoang-duc.nguyen/Projects",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "relative-numbers": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atom-material-syntax, v0.4.0
atom-material-ui, v0.8.1
atom-terminal, v0.8.0
atom-ternjs, v0.13.2
autocomplete-paths, v1.0.2
clipboard-plus, v0.5.1
custom-title, v1.0.1
docblockr, v0.7.3
emmet, v2.4.1
file-icons, v1.6.14
git-diff-details, v0.22.0
highlight-selected, v0.11.2
language-babel, v2.15.4
language-gitignore, v0.2.0
language-haml, v0.23.15
language-rspec, v0.5.0
linter, v1.11.3
linter-js-yaml, v1.2.5
linter-rubocop, v0.4.7
linter-scss-lint, v2.5.1
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
minimap-split-diff, v0.3.0
nerd-treeview, v0.3.1
pigments, v0.24.1
project-find-navigation, v0.0.9
project-manager, v2.7.6
rails-model-schema, v0.7.3
recent-files-fuzzy-finder, v0.2.4
regex-railroad-diagram, v0.11.0
relative-numbers, v0.5.0
remember-file-positions, v0.2.1
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
symbol-gen, v1.0.0
terminal-plus, v0.14.5
vim-mode-plus, v0.21.2
vim-mode-plus-move-selected-text, v0.3.0
vim-mode-plus-move-to-symbols, v0.1.4
vim-mode-plus-subword-movement, v0.2.2
wordcount, v2.6.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by dawsonbotsford** [comment]
Same issue. So incredible annoying. I know the text editor was destroyed, that's exactly what's supposed to happen with the `relative-numbers

**Comment by yriveiro** [comment]
+1
