### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by oivva** [justmoon/relative-numbers#2]
Conflict with move-panes package.
Try to move active tab to different panes.

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [relative-numbers](https://github.com/justmoon/relative-numbers) package, v0.2.4

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At C:\Tools\Atom\resources\app.asar\src\gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (C:\Tools\Atom\resources\app.asar\src\gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (C:\Tools\Atom\resources\app.asar\src\text-editor.js:2594:35)
    at new LineNumberView (file:///C:/Users/i.oleksandrov/Dropbox/Settings/Atom/.atom/packages/relative-numbers/lib/line-number-view.coffee:10:23)
    at file:///C:/Users/i.oleksandrov/Dropbox/Settings/Atom/.atom/packages/relative-numbers/lib/relative-numbers.coffee:20:11
    at C:\Tools\Atom\resources\app.asar\src\workspace.js:287:16
    at C:\Tools\Atom\resources\app.asar\src\workspace.js:352:18
    at Emitter.module.exports.Emitter.emit (C:\Tools\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Tools\Atom\resources\app.asar\src\pane-container.js:375:27)
    at C:\Tools\Atom\resources\app.asar\src\pane-container.js:359:28
    at Emitter.module.exports.Emitter.emit (C:\Tools\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
```

### Commands

```
  3x -0:26.5.0 vim-mode:move-down (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  6x -0:25.9.0 vim-mode:move-up (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  3x -0:24.4.0 vim-mode:move-right (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
 20x -0:23.8.0 vim-mode:move-down (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  8x -0:19 vim-mode:move-up (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:17.5.0 vim-mode:move-to-start-of-file (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
  3x -0:17.3.0 vim-mode:move-down (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:14.3.0 move-panes:move-right (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "bookmarks",
      "go-to-line",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "metrics",
      "welcome"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
move-panes, v0.2.0
pain-split, v1.4.0
relative-numbers, v0.2.4
vim-mode, v0.63.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by LinuCC** [comment]
+1, still exists on atom 1.3.2  and relative-numbers v0.4.1 on Linux.

**Comment by andycmaj** [comment]
+1

[Enter steps to reproduce below:]

1. turn on relative numbers
2. run move-right command 

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11
**Thrown From**: [relative-numbers](https://github.com/justmoon/relative-numbers) package, v0.5.0


### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2701:35)
    at new LineNumberView (/Users/acunningham/.atom/packages/relative-numbers/lib/line-number-view.coffee:14:23)
    at /Users/acunningham/.atom/packages/relative-numbers/lib/relative-numbers.coffee:30:11
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:295:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:360:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:359:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:355:20)
    at Object.module.exports.swapEditor (/Users/acunningham/.atom/packages/move-panes/lib/move-panes.coffee:40:12)
    at Object.module.exports.move (/Users/acunningham/.atom/packages/move-panes/lib/move-panes.coffee:35:8)
    at Object.module.exports.moveRight (/Users/acunningham/.atom/packages/move-panes/lib/move-panes.coffee:11:18)
    at atom-workspace.atom.commands.add.move-panes:move-right (/Users/acunningham/.atom/packages/move-panes/lib/move-panes.coffee:4:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:30 blur (atom-text-editor.editor.omnisharp-editor.normal-mode.is-focused)
     -1:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:29.2.0 blur (atom-text-editor.editor.mini.is-focused)
  4x -1:25.4.0 vim-mode-plus:move-down (atom-text-editor.editor.omnisharp-editor.normal-mode.vim-mode-plus.is-focused)
     -1:20.8.0 advanced-open-file:toggle (atom-text-editor.editor.omnisharp-editor.normal-mode.vim-mode-plus.is-focused)
     -1:20.8.0 blur (atom-text-editor.editor.omnisharp-editor.normal-mode.vim-mode-plus.is-focused)
  2x -1:18.9.0 advanced-open-file:autocomplete (atom-text-editor.path-input.editor.mini.is-focused)
     -0:36.1.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
  5x -0:36.1.0 blur (atom-text-editor.path-input.editor.mini.is-focused)
     -0:33.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.omnisharp-editor.is-focused)
     -0:33.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.omnisharp-editor.is-focused)
     -0:23 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:23 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23 blur (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 move-panes:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.omnisharp-editor.is-focused)
  2x -0:19.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "vim-mode",
      "vim-surround",
      "json-schema",
      "language-aspx",
      "language-cshtml"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "language-csharp"
    ],
    "themes": [
      "one-dark-ui",
      "base16-papercolor-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.2
atom-yeoman, v0.3.15
base16-papercolor-dark-syntax, v0.2.0
character-table, v0.4.3
file-icons, v1.6.16
language-cs, v0.1.1
language-docker, v1.1.6
linter, v1.11.3
linter-docker, v0.1.2
move-panes, v0.2.0
omnisharp-atom, v0.26.13
relative-numbers, v0.5.0
vim-mode-plus, v0.21.3

# Dev
language-csharp, v0.11.0
```
