### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by yriveiro** [justmoon/relative-numbers#7]
[Enter steps to reproduce below:]

1. Copy paste a xml to pane

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [relative-numbers](https://github.com/justmoon/relative-numbers) package, v0.3.0

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:803

RangeError: Invalid array length
    at LineNumberView.module.exports.LineNumberView._spacer (/Users/yriveiro/.atom/packages/relative-numbers/lib/line-number-view.coffee:48:5)
    at LineNumberView.module.exports.LineNumberView._update (/Users/yriveiro/.atom/packages/relative-numbers/lib/line-number-view.coffee:82:23)
    at /Users/yriveiro/.atom/packages/relative-numbers/lib/line-number-view.coffee:1:1
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1644:27)
    at Selection.module.exports.Selection.markerDidChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/selection.js:926:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:392:20)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:299:27
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:295:46)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1291:35)
    at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:812:12)
    at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1202:26)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:796:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2082:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2044:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:794:19)
    at TextEditor.module.exports.TextEditor.pasteText (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2483:19)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:paste (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:353:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:573:34
    at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:798:18)
    at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1202:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:572:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:55.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
     -0:13.2.0 tree-view:duplicate (span.name.icon.icon-file-text)
     -0:10.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:09.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
     -0:03.9.0 core:select-all (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.4.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "git-tab-status",
      "hyperclick",
      "wrap-guide",
      "autocomplete-php"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/yriveiro/Development/github/"
  },
  "relative-numbers": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.4
atom-cli-diff, v1.1.0
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-pair, v2.0.10
autocomplete-paths, v1.0.2
autocomplete-phpunit, v1.0.2
color-picker, v2.0.14
color-tabs, v0.1.8
docblockr, v0.7.3
file-icons, v1.6.13
git-diff-details, v0.21.0
go-plus, v3.5.2
highlight-line, v0.11.0
inline-messenger, v1.2.8
language-rust, v0.4.5
linter, v1.11.3
linter-jsonlint, v1.1.2
linter-rust, v0.3.0
linter-shellcheck, v1.0.2
local-history, v3.2.3
markdown-format, v2.5.1
minimap, v4.18.4
minimap-bookmarks, v0.2.0
minimap-git-diff, v4.1.8
multi-wrap-guide, v0.23.4
php-cs-fixer, v2.5.1
phpunit, v1.2.0
phpunit-snippets, v0.1.0
pigments, v0.19.5
pretty-json, v0.4.1
relative-numbers, v0.3.0
rust-api-docs-helper, v0.5.1
seti-syntax, v0.4.1
synced-sidebar, v0.4.3
travis-ci-status, v0.18.0
vim-mode, v0.64.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by justmoon** [comment]
Added a patch that should fix the exception. Wasn't able to figure out what caused it though, so if you're seeing visual glitches (line numbers are not correctly indented/spaced) please let me know.
